## Step 1: Preprocess the Data

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN","NAME"])
application_df.head(5)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df["APPLICATION_TYPE"].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Based on the Starter_Code information, an appropriate cutoff = 300
application_types_to_replace = list(app_type_count[app_type_count < 300].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classif_count = application_df["CLASSIFICATION"].value_counts()
classif_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classif_count[classif_count > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

# Based on the Starter_Code information, an appropriate cutoff = 800
classifications_to_replace = list(classif_count[classif_count < 800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
# Based on the Starter_Code, our target is IS_SUCCESSFUL
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns="IS_SUCCESSFUL")
print(y.value_counts())

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=13)

1    18261
0    16038
Name: IS_SUCCESSFUL, dtype: int64

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
X_train_scaled[0]

array([ 0.01394306, -0.03328823, -0.09072362, -0.1240739 , -0.17448163,
        0.51859655, -0.22091482, -0.18831544, -0.19226381, -0.14753563,
       -0.14767311,  1.09362003, -0.04091931, -1.08670333, -0.03180805,
       -0.01079982, -0.01870803, -1.01259683, -0.40585679,  2.17086066,
       -0.24099443, -0.24503139, -0.26525758, -0.10565757, -0.06553264,
       -0.01079982,  0.47028987, -0.44562713, -0.65215817, -0.11930353,
       -0.03529198,  0.67604561,  0.63825934, -0.14753563, -0.12615722,
       -0.33027252, -0.08323705, -0.17090058, -0.35032906, -0.06432508,
       -0.07397412,  0.02991499, -0.02991499])

In [13]:
X_test_scaled[0]

array([ 0.01394306, -0.03328823, -0.09072362, -0.1240739 , -0.17448163,
        0.51859655, -0.22091482, -0.18831544, -0.19226381, -0.14753563,
       -0.14767311, -0.91439437, -0.04091931,  0.92021435, -0.03180805,
       -0.01079982, -0.01870803,  0.98755988, -0.40585679, -0.46064679,
       -0.24099443, -0.24503139, -0.26525758, -0.10565757, -0.06553264,
       -0.01079982,  0.47028987, -0.44562713, -0.65215817, -0.11930353,
       -0.03529198,  0.67604561,  0.63825934, -0.14753563, -0.12615722,
       -0.33027252, -0.08323705, -0.17090058, -0.35032906, -0.06432508,
       -0.07397412,  0.02991499, -0.02991499])

## Step 2: Compile, Train, and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# Based on Starter_Code, we can see that first_nodes = 80, second_nodes = 30
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = 80, input_shape=(X_train.shape[1],), activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = 30, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
# Train the model
# Starting with 50 fit epochs
nn_fit = nn.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 6s 4ms/step - loss: 0.5676 - accuracy: 0.7227
Epoch 2/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7294
Epoch 3/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5528 - accuracy: 0.7300
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7304
Epoch 5/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7327
Epoch 6/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7339
Epoch 7/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7331
Epoch 8/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7338
Epoch 9/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7334
Epoch 10/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7355
Epoch 11/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7336
Epoch 12/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7342
Epoch 13/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7353
Epoch 14/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7345
Epoch 15/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 16/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7358
Epoch 17/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7358
Epoch 18/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7358
Epoch 19/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7354
Epoch 20/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7367
Epoch 21/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7364
Epoch 22/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7365
Epoch 23/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7355
Epoch 24/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7367
Epoch 25/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7375

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 [==============================] - 1s 1ms/step - loss: 0.5509 - accuracy: 0.7317
Loss: 0.5509375929832458, Accuracy: 0.7316617965698242

In [18]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")
nn.save("AlphabetSoupCharity.keras")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(